services:
  python:
    image: sample/python:1.0
    build: ./python
    container_name: 'sample-python'
    stdin_open: true
    tty: true
    working_dir: '/tmp/work'
    volumes:
    - ../python:/tmp/work